apiVersion: v1
kind: ResourceQuota
metadata:
  name: formacion-quota
  namespace: lgp-formacion
spec:
  hard:
    pods: 10
    requests.cpu: 4000m
    requests.memory: 8Gi
    resourcequotas: 1
    requests.storage: 50Gi
    persistentvolumeclaims: 5
