apiVersion: extensions/v1beta1
kind: ReplicaSet
metadata:
  labels:
    app: nginx
  name: nginx-rs
  namespace: lgp-formacion
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
