apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: nginx
  namespace: lgp-formacion
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      nodeSelector:
        app: nginx
      containers:
        - name: nginx
          image: nginx
          ports:
          - containerPort: 80
     nodeSelector:
        master: "true"
