apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: nginx
  name: nginx-rc
  namespace: lgp-formacion
spec:
  replicas: 3
  selector:
    app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
          name: http
