apiVersion: v1
kind: Pod
metadata:
  name: cm-envar-demo
  namespace: lgp-formacion
  labels:
    purpose: demonstrate-cm-envars
spec:
  containers:
  - name: cm-envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    envFrom:
    - configMapRef:
        name: special-config
