apiVersion: v1
kind: Pod
metadata:
  name: sec-envar-demo
  namespace: lgp-formacion
  labels:
    purpose: demonstrate-sec-envars
spec:
  containers:
  - name: sec-envar-demo-container
    image: gcr.io/google-samples/node-hello:1.0
    env:
    - name: DEMO_GREETING
      value: "Hello from the environment"
    - name: DEMO_FAREWELL
      value: "Such a sweet sorrow"
    - name: DEMO_SECRET_USER
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: username
    - name: DEMO_SECRET_PASS
      valueFrom:
        secretKeyRef:
          name: test-secret
          key: password
