apiVersion: apps/v1
kind: Deployment
metadata:
  name: twistlock-console
  namespace: twistlock
  labels:
    name: twistlock-console
spec:
  replicas: 1
  selector:
    matchLabels:
      name: twistlock-console
  strategy:
    type: Recreate
  template:
    metadata:
      name: twistlock-console
      namespace: twistlock
      labels:
        name: twistlock-console
    spec:
      restartPolicy: Always
      serviceAccountName: twistlock-console
      containers:
      - name: twistlock-console
        image: registry-auth.twistlock.com/tw_n5aq46hm0txc9g8b8ctc9kdwjvyuym7z/twistlock/console:console_19_07_363
        ports:
        - name: mgmt-https
          containerPort: 8083
        - name: communication
          containerPort: 8084
        - name: mgmt-http
          containerPort: 8081
        env:
        - name: CONSOLE_CN
          value: ""
        - name: HIGH_AVAILABILITY_ENABLED
          value: "false"
        - name: CONFIG_PATH
          value: /data/config/twistlock.cfg
        - name: LOG_PROD
          value: "true"
        - name: DATA_RECOVERY_ENABLED
          value: "true"
        - name: COMMUNICATION_PORT
          value: "8084"
        - name: MANAGEMENT_PORT_HTTPS
          value: "8083"
        - name: MANAGEMENT_PORT_HTTP
          value: "8081"
        - name: SCAP_ENABLED
          value: ""
        securityContext:
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: twistlock-config-volume
          mountPath: "/data/config/"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock"
          subPath: "var/lib/twistlock"
        - name: console-persistent-volume
          mountPath: "/var/lib/twistlock-backup"
          subPath: "var/lib/twistlock-backup"
        - name: syslog-socket
          mountPath: "/dev/log"
      volumes:
      - name: console-persistent-volume
        persistentVolumeClaim:
          claimName: twistlock-console
      - name: syslog-socket
        hostPath:
          path: "/dev/log"
      - name: twistlock-config-volume
        configMap:
          name: twistlock-console
